'''
Data Engineering: Frozen Expert Target Manifold (Y-Encoder)

This script parses the reasoning chains generated by the Gemini (Flash-Preview) API and maps 
them strictly into continuous, geometric target topologies.

By freezing an LLM-native text embedding model (`Qwen3-0.6B`) as the Target Predictor (Y-Encoder),
it preserves the distinct syntax/structural logic required to reconstruct discrete symbols 
(like calculations). The target targets (in shape [batch, K, target_dim]) are saved directly 
to `<output_dir>` as PyTorch tensor files (`.pt`) for Continuous Alignment via `train_x_encoder.py`.
'''

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, AutoModelForImageTextToText, AutoProcessor
import json
import re


import argparse
import os
import yaml

def load_qwen_target_model(model_id: str, device="cuda" if torch.cuda.is_available() else "cpu"):
    print(f"Loading {model_id} for Target Manifold extraction on {device}...")
    tokenizer = AutoTokenizer.from_pretrained(model_id)
    
    # Select the correct model class based on whether it is a VLM or a pure LLM
    is_vlm = "VL" in model_id
    ModelClass = AutoModelForImageTextToText if is_vlm else AutoModelForCausalLM
    
    # CPU fallback compatible loading
    if device == "cpu":
        model = ModelClass.from_pretrained(
            model_id, 
            torch_dtype=torch.float32
        )
    else:
        model = ModelClass.from_pretrained(
            model_id, 
            torch_dtype=torch.bfloat16,
            device_map="auto"
        )
    model.eval()
    if device == "cpu":
        model = model.to(device)
        
    try:
        processor = AutoProcessor.from_pretrained(model_id)
    except Exception as e:
        print(f"Warning: Could not load AutoProcessor for {model_id}. Text fallback only.")
        processor = None
        
    return tokenizer, processor, model

def parse_k4_steps(reasoning_text: str):
    """Extracts exactly 4 steps cumulatively from the LLM output."""
    steps = []
    # Simple regex to split based on "Step X:" formatting constraint
    parts = re.split(r'Step \d+.*?\]?:', reasoning_text)
    
    cumulative_text = ""
    for p in parts[1:]: # Skip text before Step 1
        clean_p = p.strip()
        if cumulative_text:
            cumulative_text += "\n" + clean_p
        else:
            cumulative_text = clean_p
        steps.append(cumulative_text)
        
    # Validation padding
    while len(steps) < 4:
        if steps:
            steps.append(steps[-1] + "\nEmpty Step")
        else:
            steps.append("Empty Step")
            
    return steps[:4]

def embed_steps_batch(texts: list[str], bases: list[str], tokenizer, model, device="cuda", images=None, processor=None):
    """Passes a batch of step texts natively through Qwen3-0.6B and extracts the final hidden states."""
    # Ensure padding is correctly applied for the batch
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
        
    if images is not None and processor is not None and any(images):
        messages_full = []
        messages_base = []
        for txt, base_txt, img in zip(texts, bases, images):
            messages_full.append([{"role": "user", "content": [{"type": "image", "image": img}, {"type": "text", "text": txt}]}])
            messages_base.append([{"role": "user", "content": [{"type": "image", "image": img}, {"type": "text", "text": base_txt}]}])
            
        prompts_full = [processor.apply_chat_template(m, tokenize=False, add_generation_prompt=True) for m in messages_full]
        prompts_base = [processor.apply_chat_template(m, tokenize=False, add_generation_prompt=True) for m in messages_base]
        
        inputs = processor(text=prompts_full, images=images, return_tensors="pt", padding=True).to(device)
        inputs_base = processor(text=prompts_base, images=images, return_tensors="pt", padding=True).to(device)
        
        base_lengths = inputs_base.attention_mask.sum(dim=1)
        full_lengths = inputs.attention_mask.sum(dim=1)
    else:
        inputs = tokenizer(texts, padding=True, return_tensors="pt").to(device)
        inputs_base = tokenizer(bases, padding=True, return_tensors="pt").to(device)
        base_lengths = inputs_base.attention_mask.sum(dim=1)
        full_lengths = inputs.attention_mask.sum(dim=1)
    
    # Calculate exact mathematical indices for the new localized step tokens
    target_mask = torch.zeros_like(inputs.attention_mask)
    for i in range(len(texts)):
        b_len = int(base_lengths[i].item())
        f_len = int(full_lengths[i].item())
        
        if tokenizer.padding_side == 'right':
            target_mask[i, b_len:f_len] = 1
        else:
            seq_len = target_mask.shape[1]
            target_mask[i, seq_len - f_len + b_len : seq_len] = 1
            
    with torch.no_grad():
        # VLM models might expect specific keyword arguments even for text-only inference
        outputs = model(
            input_ids=inputs.input_ids,
            attention_mask=inputs.attention_mask,
            pixel_values=inputs.get("pixel_values"),
            image_grid_thw=inputs.get("image_grid_thw"),
            output_hidden_states=True,
            return_dict=True
        )
        # Extract the hidden states from the last layer [batch, seq_len, hidden_dim]
        hidden_states = outputs.hidden_states[-1]
        
        # Apply Attention-Weighted Mean Pooling strictly over the localized target_mask tokens
        target_mask = target_mask.unsqueeze(-1).to(hidden_states.dtype)
        # Multiply states by mask to isolate the new target logic tokens, then sum
        sum_embeddings = torch.sum(hidden_states * target_mask, dim=1)
        # Divide by the actual step sequence length to get the precise local mean
        sum_mask = torch.clamp(target_mask.sum(dim=1), min=1e-9)
        mean_pooled_embeddings = sum_embeddings / sum_mask
    
    return mean_pooled_embeddings.cpu()

def build_manifold(model_id: str, input_jsonl: str, output_dir: str):
    """Processes K4 text and saves continuous target tensors."""
    os.makedirs(output_dir, exist_ok=True)
    device = "cuda" if torch.cuda.is_available() else "cpu"
    tokenizer, processor, model = load_qwen_target_model(model_id, device)
    
    batch_size = config.get("build_manifold", {}).get("batch_size", 4)
    print(f"Processing with chunked batch_size: {batch_size}")
    
    with open(input_jsonl, 'r') as f:
        lines = f.readlines()
        
    for i in range(0, len(lines), batch_size):
        batch_lines = lines[i:i+batch_size]
        batch_data = [json.loads(line) for line in batch_lines]
        
        flat_steps = []
        flat_bases = []
        flat_images = []
        for data in batch_data:
            q_text = data["question"].replace("<image>", "").strip()
            # Safety cleanup just in case thought tokens exist in raw data
            for k in range(1, 5):
                q_text = q_text.replace(f"<thought_{k}>", "")
                
            prefix = f"{q_text}\nAnswer: "
            img_path = data.get("image_path")
            
            base = prefix
            cumulative_steps = parse_k4_steps(data["reasoning"])
            for step_text in cumulative_steps:
                flat_bases.append(base)
                flat_steps.append(f"{prefix}{step_text}")
                flat_images.append(img_path)
                base = f"{prefix}{step_text}"
            
        # Process all steps in a single batched matrix multiplication
        target_tensors_flat = embed_steps_batch(flat_steps, flat_bases, tokenizer, model, device=device, images=flat_images, processor=processor)
        
        # Reshape isolated K-thought vectors back into exact topological instances
        target_tensors = target_tensors_flat.view(len(batch_data), 4, -1)
        
        # Save the isolated .pt files for Phase 3 training
        for j, tensor in enumerate(target_tensors):
            idx = i + j
            torch.save(tensor.clone(), os.path.join(output_dir, f"problem_{idx}_targets.pt"))
            
        if (i + len(batch_data)) % 50 < batch_size:
            print(f"Generated manifolds for {i + len(batch_data)} problems...")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Extract continuous manifold targets.")
    parser.add_argument("--config", type=str, default="training/config.yaml")
    parser.add_argument("--experiment_name", type=str, default=None, help="Explicit experiment namespace override.")
    parser.add_argument("--model_id", type=str, default=None, help="Explicit target base LLM override.")
    parser.add_argument("--input_jsonl", type=str, default=None, help="Explicit JSONL source override.")
    parser.add_argument("--output_dir", type=str, default=None, help="Explicit target tensor save dir override.")
    args = parser.parse_args()
    
    with open(args.config, 'r') as f:
        config = yaml.safe_load(f)
        
    experiment_name = args.experiment_name or config.get("experiment", {}).get("name", "default")
    model_id = args.model_id or config["model"]["target_model_id"]
    input_jsonl = args.input_jsonl or config["data"]["jsonl_path"]
    
    output_dir = args.output_dir
    if output_dir is None:
        base_dir = config.get("data", {}).get("targets_dir", "/workspace/target_tensors")
        output_dir = os.path.join(base_dir, f"target_tensors_{experiment_name}")
        
    # Inject directly into config dictionary for transparent logging
    if "data" not in config: config["data"] = {}
    config["data"]["targets_dir"] = output_dir

    print("\n" + "="*50)
    print("LatentEuclid Phase 3 (Continuous Manifold Target Generation)")
    print("Executing with Configuration:")
    print(yaml.dump(config, default_flow_style=False))
    print("="*50 + "\n")
        
    print(f"Dynamically routing Target Tensors to: {output_dir}")
    build_manifold(model_id, input_jsonl, output_dir)
