'''
Data Engineering: Frozen Expert Target Manifold (Y-Encoder)

This script parses the reasoning chains generated by the Gemini (Flash-Preview) API and maps 
them strictly into continuous, geometric target topologies.

By freezing an LLM-native text embedding model (`Qwen3-0.6B`) as the Target Predictor (Y-Encoder),
it preserves the distinct syntax/structural logic required to reconstruct discrete symbols 
(like calculations). The target targets (in shape [batch, K, target_dim]) are saved directly 
to `<output_dir>` as PyTorch tensor files (`.pt`) for Continuous Alignment via `train_x_encoder.py`.
'''

import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, AutoModelForImageTextToText
import json
import re


import argparse
import os

def load_qwen_target_model(model_id: str, device="cuda" if torch.cuda.is_available() else "cpu"):
    print(f"Loading {model_id} for Target Manifold extraction on {device}...")
    tokenizer = AutoTokenizer.from_pretrained(model_id)
    
    # Select the correct model class based on whether it is a VLM or a pure LLM
    is_vlm = "VL" in model_id
    ModelClass = AutoModelForImageTextToText if is_vlm else AutoModelForCausalLM
    
    # CPU fallback compatible loading
    if device == "cpu":
        model = ModelClass.from_pretrained(
            model_id, 
            torch_dtype=torch.float32
        )
    else:
        model = ModelClass.from_pretrained(
            model_id, 
            torch_dtype=torch.bfloat16,
            device_map="auto"
        )
    model.eval()
    if device == "cpu":
        model = model.to(device)
    return tokenizer, model

def parse_k4_steps(reasoning_text: str):
    """Extracts exactly 4 steps from the LLM output."""
    steps = []
    # Simple regex to split based on "Step X:" formatting constraint
    parts = re.split(r'Step \d+.*?\]?:', reasoning_text)
    for p in parts[1:]: # Skip text before Step 1
        steps.append(p.strip())
        
    # Validation padding
    while len(steps) < 4:
        steps.append("Empty Step")
    return steps[:4]

def embed_steps_batch(texts: list[str], tokenizer, model, device="cuda"):
    """Passes a batch of step texts natively through Qwen3-0.6B and extracts the final hidden states."""
    # Ensure padding is correctly applied for the batch
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
        
    inputs = tokenizer(texts, padding=True, return_tensors="pt").to(device)
    
    with torch.no_grad():
        # VLM models might expect specific keyword arguments even for text-only inference
        outputs = model(
            input_ids=inputs.input_ids,
            attention_mask=inputs.attention_mask,
            output_hidden_states=True,
            return_dict=True
        )
        # Extract the hidden states from the last layer [batch, seq_len, hidden_dim]
        hidden_states = outputs.hidden_states[-1]
        
        # Instead of extracting the anisotropic final token, apply Attention-Weighted Mean Pooling
        # to capture the holistic bidirectional semantic embedding of the entire reasoning step
        attention_mask = inputs.attention_mask.unsqueeze(-1).to(hidden_states.dtype)
        # Multiply states by mask to zero out padded tokens, then sum
        sum_embeddings = torch.sum(hidden_states * attention_mask, dim=1)
        # Divide by the actual sequence length (sum of mask) to get the mean
        sum_mask = torch.clamp(attention_mask.sum(dim=1), min=1e-9)
        mean_pooled_embeddings = sum_embeddings / sum_mask
    
    return mean_pooled_embeddings.cpu()

def build_manifold(model_id: str, input_jsonl: str, output_dir: str):
    """Processes K4 text and saves continuous target tensors."""
    os.makedirs(output_dir, exist_ok=True)
    device = "cuda" if torch.cuda.is_available() else "cpu"
    tokenizer, model = load_qwen_target_model(model_id, device)
    
    with open(input_jsonl, 'r') as f:
        for idx, line in enumerate(f):
            data = json.loads(line)
            steps = parse_k4_steps(data["reasoning"])
            
            # Process all 4 steps in a single batched matrix multiplication
            target_tensor = embed_steps_batch(steps, tokenizer, model, device=device)
            
            # Save the .pt file for Phase 3 training
            torch.save(target_tensor, os.path.join(output_dir, f"problem_{idx}_targets.pt"))
            
            if (idx + 1) % 50 == 0:
                print(f"Generated manifolds for {idx + 1} problems...")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Extract continuous manifold targets.")
    parser.add_argument("--model_id", type=str, default="Qwen/Qwen3-0.6B")
    parser.add_argument("--input_jsonl", type=str, default="data/geothoughts_k4_gemini3.1.jsonl")
    parser.add_argument("--output_dir", type=str, default="/workspace/target_tensors/v2_mean_pooled/")
    args = parser.parse_args()
    
    build_manifold(args.model_id, args.input_jsonl, args.output_dir)
